"""Add dietary columns to MenuItem

Revision ID: 3fafa2a03ef7
Revises: 9a091d27955a
Create Date: 2025-08-18 15:07:38.344813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fafa2a03ef7'
down_revision = '9a091d27955a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vegetarian', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('is_vegan', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('is_gluten_free', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('is_nut_free', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.alter_column('is_vegetarian',
               existing_type=sa.Boolean(),
               nullable=False,
               server_default=sa.false())
        batch_op.alter_column('is_vegan',
                existing_type=sa.Boolean(),
                nullable=False,
                server_default=sa.false())
        batch_op.alter_column('is_gluten_free',
                existing_type=sa.Boolean(),
                nullable=False,
                server_default=sa.false())
        batch_op.alter_column('is_nut_free',
                existing_type=sa.Boolean(),
                nullable=False,
                server_default=sa.false())
        batch_op.create_index(op.f('ix_menu_item_is_vegetarian'), ['is_vegetarian'], unique=False)
        batch_op.create_index(op.f('ix_menu_item_is_vegan'), ['is_vegan'], unique=False)
        batch_op.create_index(op.f('ix_menu_item_is_gluten_free'), ['is_gluten_free'], unique=False)
        batch_op.create_index(op.f('ix_menu_item_is_nut_free'), ['is_nut_free'], unique=False)
        batch_op.create_index(op.f('ix_menu_item_available'), ['available'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_column('is_nut_free')
        batch_op.drop_column('is_gluten_free')
        batch_op.drop_column('is_vegan')
        batch_op.drop_column('is_vegetarian')

    # ### end Alembic commands ###
