"""Added new fields or tables

Revision ID: 932937043aa8
Revises: d805f6207782
Create Date: 2025-09-24 12:09:52.678850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '932937043aa8'
down_revision = 'd805f6207782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item')
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
        batch_op.alter_column('is_vegetarian',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_vegan',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_gluten_free',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_nut_free',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('monthly_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('total_orders', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_revenue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('average_order_value', sa.Float(), nullable=True))
        batch_op.create_unique_constraint('unique_restaurant_date', ['restaurant_id', 'date'])
        batch_op.drop_column('month')
        batch_op.drop_column('created_at')
        batch_op.drop_column('total_payment')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items_json', sa.Text(), nullable=False))
        batch_op.alter_column('customer_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
        batch_op.alter_column('customer_phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=15),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_column('items')

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('review_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('seats',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table', schema=None) as batch_op:
        batch_op.alter_column('seats',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('number',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('review_ibfk_2'), 'order', ['order_id'], ['id'])
        batch_op.alter_column('rating',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('items', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False))
        batch_op.alter_column('total',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('customer_phone',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False)
        batch_op.alter_column('customer_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
        batch_op.drop_column('items_json')

    with op.batch_alter_table('monthly_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_payment', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('month', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False))
        batch_op.drop_constraint('unique_restaurant_date', type_='unique')
        batch_op.drop_column('average_order_value')
        batch_op.drop_column('total_revenue')
        batch_op.drop_column('total_orders')
        batch_op.drop_column('date')

    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.alter_column('is_nut_free',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_gluten_free',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_vegan',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_vegetarian',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)

    op.create_table('order_item',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('menu_item_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name=op.f('order_item_ibfk_2')),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('order_item_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
