"""Create restaurant_settings table

Revision ID: d805f6207782
Revises: 3fafa2a03ef7
Create Date: 2025-08-20 04:18:58.631684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd805f6207782'
down_revision = '3fafa2a03ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('bank_account_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account_number', sa.String(length=100), nullable=True),
    sa.Column('ifsc_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('razorpay_merchant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_item_available'))
        batch_op.drop_index(batch_op.f('ix_menu_item_is_gluten_free'))
        batch_op.drop_index(batch_op.f('ix_menu_item_is_nut_free'))
        batch_op.drop_index(batch_op.f('ix_menu_item_is_vegan'))
        batch_op.drop_index(batch_op.f('ix_menu_item_is_vegetarian'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_item_is_vegetarian'), ['is_vegetarian'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_item_is_vegan'), ['is_vegan'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_item_is_nut_free'), ['is_nut_free'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_item_is_gluten_free'), ['is_gluten_free'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_item_available'), ['available'], unique=False)

    op.drop_table('restaurant_settings')
    # ### end Alembic commands ###
